### PR TITLE
Do not store URLencoded password

### PR DESCRIPTION
**Pull request by gtenagli**
Tentative fix for #220, please excuse my not being proficient in JS.

### CODE REVIEW

**Comment by bavincen** [comment]
Can you try base64 instead? if that work?

**Comment by gtenagli** [comment]
Hi! Why do you think it is unsafe to save as normal text? In order to prevent messing up with the EWS URL?

**Comment by muthusuba** [comment]
This patch seems good to me. :+1:

**Comment by muthusuba** [comment]
@gtenagli Thank you!

**Comment by bavincen** [comment]
This one is buggy.. we unable to use spaces in password 
@gtenagli

**Comment by bavincen** [comment]
I have reverted it. please give a new pull request with working mechanism ..

**Pull request merged**
