### PR TITLE
Update mivExchangeAutoCompleteSearch.js

### PR DESCRIPTION
**Pull request by dimania**
autocomplete for encoded characters (other then english lang)

### CODE REVIEW

**Comment by bavincen** [comment]
@dimania are you sure this file need to be changes??

**Comment by bavincen** [comment]
This is not required for address book.. this is autocomplete which not usable now. can you fix this.
FYI this is not called during startup. this feature allows you autocomplete in compose mail window..

**Comment by bavincen** [comment]
It is xpcom.

**Comment by dimania** [comment]
Yes this need for autocomplete in compose mail window.
Without tihs autocomplete other then english lang don't work.

**Pull request merged**
