### PR TITLE
Enabled editing server address box

### PR DESCRIPTION
**Pull request by nikmit**
My first steps on this one so treading gently :)
Could not add the address of the office365 server as the address box was disabled. Enabled in the least intrusive way I could think of  and I have it up and running now.

### CODE REVIEW

**Comment by bavincen** [comment]
hmm this doesnt solve the problem acually. you have to code js too.
This is dynamically enabling/disabling so..
Also same work in addressbook window too

**Comment by muthusuba** [comment]
@nikmit Welcome to the project :) Thank you so much for the patch!

What @bavincen seems to say is:
a) if you just change the view/xml file - the code might override it and may not work in all cases
b) you might also want it to be consistent with other dialog boxes like addressbook window

**Comment by nikmit** [comment]
Thanks for the replies :)
Hopefully this is useful to the project as a bug report. It did get things working for me, and I'm loving the addon. Recommended to the team. Thanks for your work!

**Comment by bavincen** [comment]
@nikmit If you would like to do more work on this,   i help you out..


:)

**Comment by nikmit** [comment]
I have done no js coding for some 10 years... worried any js code I contribute will cause more harm than help :p

**Pull request closed without merging**
