### PR TITLE
Some typeahead fixes mostly related to distribution lists

### PR DESCRIPTION
**Pull request by dannybaumann**

### CODE REVIEW

**Comment by bavincen** [comment]
hello @dannybaumann Thanks a lot for you patch, 
may i know the target issue
i guess  address completion #118 ?

**Comment by dannybaumann** [comment]
No, address completion in itself is working fine for me. The issue just is that when attempting to autocomplete distribution list names, they're shown in a weird way (the name isn't displayed, but instead a list of all recipients is shown).

The root cause for that is the that the distribution list results in our setup have the following format:
<t:Resolution xmlns:s="...">
  <t:Mailbox>
    <t:Name>[displayname]</t:Name>
    <t:EmailAddress>[name]@[domain]</t:EmailAddress>
    <t:RoutingType>SMTP</t:RoutingType>
    <t:MailboxType>PublicDL</t:MailboxType>
  </t:Mailbox>
  <t:Contact>
    <t:DisplayName>[displayname]</t:DisplayName>
    <t:EmailAddresses>
      <t:Entry Key="EmailAddress1">CCMAIL:[name] at [location]</t:Entry>
      <t:Entry Key="EmailAddress2">faxmaker:[name]@[location].[domain]</t:Entry>
      <t:Entry Key="EmailAddress3">MS:[domain]/[location]/[name]</t:Entry>
    </t:EmailAddresses>
    <t:ContactSource>ActiveDirectory</t:ContactSource>
    <t:Alias>[name]</t:Alias>
    <t:DirectoryId>[uuid]</t:DirectoryId>
  </t:Contact>
</t:Resolution>

As the mailbox record wasn't used, but the contact one instead, the primary email address was filled with an invalid one, leading to the getValueAt() function in mivExchangeAutoCompleteResult.js expanding the recipient list. That was unnecessary, as there was actual valid information in the mailbox record.
At first I wasn't sure whether that's intentional or a bug, but seeing how the _contactsFoundOk function in exchangeAbDistListDirectory.js also passes the mailbox to convertExchangeDistListToCard() I concluded it's a bug.


The other two commits were just stuff I stumbled upon during debugging the first item.

Speaking of autocompletion, I think it would be useful if the completion result showed the number of recipients if it's a distribution list, like "My distribution list <distlist@org.com> [5 recipients]". Do you agree? If yes, I can open a separate PR for that.

**Comment by muthusuba** [comment]
@dannybaumann Thank you! We would like to test this on our setup, to make sure it doesn't break some functionality for us - we'll  take a few days, please? Thanks again for the nice patch!

**Comment by bavincen** [comment]
Thanks!

**Pull request merged**
