### PR TITLE
Fix os dependently icon problem

### PR DESCRIPTION
**Pull request by mariolorenz**
Dear Sir, i wrote to you this issue:
https://github.com/Ericsson/exchangecalendar/issues/250

Here is my solution:
I transfer the OS-dependently CSS-Versions of "attachments-view.css" in the pathstructre:
chrome/skins/calendar/unix/
chrome/skins/calendar/win/
chrome/skins/calendar/winaero/
chrome/skins/calendar/mac/
I add the skins in die "chrome.manifest"
The css in the attachments-view.css, i've got from the OS-dependently CSS-Versions of "calendar-event-dialog.css" from the lightning-Addon:
\chrome\skin\windows\calendar\win-aero\calendar-event-dialog.css
\chrome\skin\windows\calendar\win-classic\calendar-event-dialog.css
\chrome\skin\osx\calendar\calendar-event-dialog.css
\chrome\skin\linux\calendar\calendar-event-dialog.css
The definition of "#exchWebService-add-attachment-button" from the exchange-Addon must be the same as defintion of #button-url from the lightning-Addon.
I've test it with my OS: Win7/64Bit Aero and it works fine.
Regards,
Mario

### CODE REVIEW

**Comment by bavincen** [comment]
hi can you try this..

```javascript
skin exchangecalendar fugue chrome/skins/fugue/
skin exchangecalendar fugue chrome/skins/fugue/unix/
skin exchangecalendar fugue chrome/skins/fugue/win/ os=WINNT
skin exchangecalendar fugue chrome/skins/fugue/winaero/ os=WINNT osversion>=6
skin exchangecalendar fugue chrome/skins/fugue/mac/ os=Darwin
```

the file structure would be
```javascript
chrome
├── content
└── skins
    └── fugue
        ├── mac
        ├── unix
        ├── win
        └── winaero

**Comment by bavincen** [comment]
please test thoroughly or it will break other css

sorry for delay..
 thanks

**Comment by bavincen** [comment]
I  found its not recognizing css under fugue folder

**Comment by bavincen** [comment]
Hi mario.
we need some more work here
 
forget about everything..

step 1: add   platform-os folders (win,mac,unix)
step 2: create a common folder, move all that fugue items to that folder whihc are comon to all the platform 

step 3: add the css/img to platform-os folder if it is common import img/css using @import..
in step3 you have to import/use url method in css for all the existing img/css

common folder path not skin path it will be just a url which will be used to import
p.s if that css files are common move them to platform-os folder..


Please use path simlar to this for common folder

https://dxr.mozilla.org/comm-central/source/calendar/base/themes/osx/calendar-daypicker.css#5

chrome.manifest entry would be like this

skin calendar-common fugue  chrome/skin/common/

Thanks

Thanks for your help





 
```javascript
skin exchangecalendar fugue chrome/skins/calendar/unix/
skin exchangecalendar fugue chrome/skins/calendar/win/ os=WINNT
skin exchangecalendar fugue chrome/skins/calendar/winaero/ os=WINNT osversion>=6
skin exchangecalendar fugue chrome/skins/calendar/mac/ os=Darwin
````

**Comment by mariolorenz** [comment]
Absolutly no problem.
I will do it on Wednesday.
Regard, Mario

**Pull request closed without merging**
