### PR TITLE
erFindCalendarItems code improvement (instead of PagedItemView)

### PR DESCRIPTION
**Pull request by Trim**
Hello,

I was testing use of PagedItemView instead of CalendarItemView and after some tests, I think the best is to keep use of CalendarView instead of PagedItemView.

Indeed, the structure of the code of [mivExchangeCalendar.js](https://github.com/Ericsson/exchangecalendar/blob/master/interfaces/exchangeCalendar/mivExchangeCalendar.js) is designed to do call of erFindCalendarItems using time period (it passes as argument a range start and a range end).

Furthermore, I've read on [StackOverflow ](http://stackoverflow.com/questions/11999781/how-to-do-paging-with-exchange-web-services-calendarview) that CalendarView make easier to treat repeting calendar items.

Finally, it seems that this project has already tried to use PagedItemView in commit 46ee1c6c3045bde974c70ec3043b7e47e2d8e4fa but then it rolled back after commit f938988edc103723afba778be605dc0587f8e0d2 to solve issue 381 (the issue came from the original bug reporter I suppose and it is sadly not any more online).

So, I've written some improvements of current code and it is the content of this PR:

* Use javascript engine to copy arrays with the [slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) method
* Remove some code duplication and make it simpler to read
* Replace dump function by log calls
* Clean useless code and variables which I supposed came from 46ee1c6c3045bde974c70ec3043b7e47e2d8e4fa

If you are Ok, I can also add a commit to fix the indentation too. It seems broken in the processing result loop.

Please let me know if you'd prefer pull requests on master or on ec-3.5 branch (I forgot to ask you with the last one).

See you,
Adrien

### CODE REVIEW

**Comment by bavincen** [comment]
Pull request to master..
Thanks

**Comment by bavincen** [comment]
Please test it. let me know if you need help there.

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/issues/374

**Comment by Trim** [comment]
Sorry, after more tests, it seems to not work correctly. I'll take more time to check why and I'll make a pull request on master.
See you.

**Pull request closed without merging**
