### PR TITLE
updated french translation (recent files added)

### PR DESCRIPTION
**Pull request by Dominique-2202**
added new files  extra-priority.dtd and  delegate-calendar-dialog.dtd for the french translation.

### CODE REVIEW

**Comment by Dominique-2202** [comment]
Updated French translation with new files in the fr-FR locale

**Comment by muthusuba** [comment]
Thank you! 
Would it be possible to rebase on master, please? Seems like there would be some merge conflicts from this pull :(

**Comment by Dominique-2202** [comment]
I just tried to compare again and I don't see the conflicts.... Please advise and point the conflicting file(s) and aline(s) thanks !

**Comment by muthusuba** [comment]
I didn't try manual - the automated github merge is disabled with:
"""We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing."""

So, I assumed there could be some conflicts - nevertheless, let me do the manual way, then....

**Comment by muthusuba** [comment]
I tried to do it manually...but looks like you haven't re-synched/merged from this repo. So, the pull requests seem to contain older patches as well...
Ref: https://github.com/Ericsson/exchangecalendar/pull/71/commits

To be sure, can you recheck if https://github.com/Ericsson/exchangecalendar/pull/71.patch is apply-able on master in this repo, please?

Thanks!

**Comment by Dominique-2202** [comment]
Hi
          Bavincen,
          
          I have re-checked the patch and it is indeed applicable on the
          Ericsson master.
          
        
      
        
        
        
          Best regards,
          
          Dominique Fillon
          
          
         
      On 1/23/2015 7:29 AM, Muthu Subramanian wrote:
    
    
      I tried to do it manually...but looks like you haven't
        re-synched/merged from this repo. So, the pull requests seem to
        contain older patches as well...
        Ref: https://github.com/Ericsson/exchangecalendar/pull/71/commits
      To be sure, can you recheck if https://github.com/Ericsson/exchangecalendar/pull/71.patch
        is apply-able on master in this repo, please?
      Thanks!
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by muthusuba** [comment]
Are you sure, please?

E.g. In https://github.com/Ericsson/exchangecalendar/pull/71.patch
the second hunk (in file: locale/exchangecalendar/fr-FR/exchangeSettings.dtd):
-<!ENTITY label.autoprocessingproperties.deletecancelleditems "Suppression automatique des évènements annulés">
 
+<!ENTITY label.autoprocessingproperties.deletecancelleditems "Suppression automatique des invitations annulées">
+<!ENTITY label.autoprocessingproperties.markeventtentative "Marquer automatiquement l'invitation comme possible et envoyer cette réponse à l'organisateur">

In already on master:
https://github.com/Ericsson/exchangecalendar/blob/master/locale/exchangecalendar/fr-FR/exchangeSettings.dtd#L46

**Comment by muthusuba** [comment]
And locale/exchangecalendar/fr-FR/delegate-calendar-dialog.dtd file is new in your patch, while it already exists in:
https://github.com/Ericsson/exchangecalendar/blob/master/locale/exchangecalendar/fr-FR/delegate-calendar-dialog.dtd

**Comment by Dominique-2202** [comment]
Please drop down this pull request, I have now build up a new one from a new fork from the master repository.

**Pull request closed without merging**
